### PR TITLE
explore backend support 

### PR DESCRIPTION
**Pull request by charblanc**

### CODE REVIEW

**Review by ploomiz — APPROVED** [review]

**Comment by ethanbb** [comment]
Idk what this means. I literally did nothing to this PR

**Comment by charblanc** [comment]
lol idk? but shall I merge?

**Comment by ethanbb** [comment]
Wait, this pull request is from master into explore/setup. That's not what you meant to do, is it?

**Comment by charblanc** [comment]
WOW. U RULE/

**Pull request closed without merging**
