### PR TITLE
Endpoint for retrieving user info

### PR DESCRIPTION
**Pull request by ploomiz**
Small change. In the browser-extension, we don't have access to the passport session and thus cannot load the user's information (groupIds, username, etc.). We send a request from the browser-extension to the `api/user` endpoint in this PR to load the user's information.

### CODE REVIEW

**Comment by psloomis** [comment]
[Show login link in sidebar when 401/unauthorized status is returned when attempting to fetch or create annotations.](https://trello.com/c/J4QIvmi9/15-show-login-link-in-sidebar-when-401-unauthorized-status-is-returned-when-attempting-to-fetch-or-create-annotations)

**Review by ethanbb — COMMENTED** [review]
OK, just want to make sure we're not putting anything in the user model that we wouldn't want the user themself to see, since they could easily see it by sending a get request.

**Comment by ploomiz** [comment]
It would actually be better to load the populated group objects associated with the user, rather than just group ids. I'm also confused about whether to load the article's groups or the user's groups for the drop-down selector that allows user to filter annotations by groups. We should talk about this when we meet next.

**Comment by charblanc** [comment]
Yah I think I agree peter. I also think that the user should only see groups that they are able to see // are a part of when viewing groups on an article. I assume this would include any public groups even if the user isn't explicitly subscribed to them?

**Comment by ethanbb** [comment]
Ah yeah, we can change it to populate the groups. I would think we want the user's groups, even if some of them don't have any annotations on the article. The user can select one of these groups and just see a blank sidebar, and then add an annotation to add the article to the group.

**Comment by ethanbb** [comment]
I think they should only see groups they're subscribed to on the sidebar, but maybe have a button to easily subscribe to or preview more public groups, with a number showing how many annotations there are in each group on the article?

**Comment by ploomiz** [comment]
[Create '/api/user' endpoint that returns the user object of the logged in user populated with the user's groups or 401 if no user is logged in.](https://trello.com/c/ehr5LOGb/29-create-api-user-endpoint-that-returns-the-user-object-of-the-logged-in-user-populated-with-the-user-s-groups-or-401-if-no-user-i)

**Comment by ethanbb** [comment]
OK this should be ready to merge now.

**Pull request merged**
